services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - project1

  consumer:
    deploy:
      replicas: 3
    build: ./Consumer
    depends_on:
      - rabbit
    networks:
      - project1
    restart: unless-stopped

  publisher:
    container_name: publisher
    build: ./Publisher
    # build: ./SignalGenerator
    depends_on:
      - rabbit
      - consumer
    networks:
      - project1
    restart: unless-stopped

  apiserver:
    build: ./APIServer
    depends_on:
      - rabbit
      - consumer
    networks:
      - project1
    restart: unless-stopped
    ports:
      - 1600:80

  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      - project1
    ports:
      - 800:27017

networks:
  project1:
    name: project1