services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    networks:
      - project1

  consumer:
    deploy:
      replicas: 3
    build: ./Consumer
    depends_on:
      - rabbit
    networks:
      - project1
    restart: unless-stopped

  publisher:
    container_name: publisher
    build: ./Publisher
    depends_on:
      - rabbit
      - consumer
    networks:
      - project1
    ports:
      - 8000:80
    restart: unless-stopped

networks:
  project1:
    name: project1